-- Migration: Add estimated_professional_grades column
-- Date: 2025-10-13
-- Description: Adds a JSONB column to store professional grading company estimates (PSA, BGS, SGC, CGC)

-- Add estimated_professional_grades column to cards table
ALTER TABLE cards
ADD COLUMN IF NOT EXISTS estimated_professional_grades JSONB DEFAULT NULL;

-- Add index for faster queries on professional grades
CREATE INDEX IF NOT EXISTS idx_cards_estimated_professional_grades
ON cards USING GIN (estimated_professional_grades);

-- Add comment for documentation
COMMENT ON COLUMN cards.estimated_professional_grades IS 'Professional grading company estimates (PSA, BGS, SGC, CGC) based on DCM grading results. Generated by professional grading AI prompt.';
