-- Add conversational_final_grade_summary column to cards table
-- This stores the 3-4 sentence overall card condition summary from the AI grader

ALTER TABLE cards
ADD COLUMN IF NOT EXISTS conversational_final_grade_summary TEXT;

-- Add comment to explain the column
COMMENT ON COLUMN cards.conversational_final_grade_summary IS
'3-4 sentence overall card condition summary synthesizing findings from all four grading categories (centering, corners, edges, surface). Generated by conversational AI grader v4.1+';
