import { PGlite } from '@electric-sql/pglite';
import { readFileSync } from 'node:fs';
import { beforeAll,afterAll,beforeEach,it,expect } from 'vitest';
let db:PGlite;
const owner='00000000-0000-4000-8000-000000000001',admin='00000000-0000-4000-8000-000000000010';
beforeAll(async()=>{
  db=new PGlite();await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role BYPASSRLS;CREATE SCHEMA auth;
    CREATE FUNCTION auth.role() RETURNS text LANGUAGE sql AS $$ SELECT 'service_role'::text $$;
    CREATE TABLE admin_users(id uuid PRIMARY KEY,is_active boolean,role text);
    INSERT INTO admin_users VALUES('${admin}',true,'moderator');
    CREATE TABLE user_credits(user_id uuid PRIMARY KEY,is_vip boolean,is_card_lover boolean,card_lover_current_period_end timestamptz);
    CREATE TABLE cards(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid,grade_status text,conversational_grading text,conversational_whole_grade numeric,
      front_path text,back_path text,category text,card_name text,serial text,grading_model text,conversational_prompt_version text,ownership_status text DEFAULT 'owned',deleted_at timestamptz);`);
  for(const file of ['20260906_grade_review_intake.sql','20260906_grade_review_processor.sql','20260906_grade_review_owner_decision.sql','20260907_manual_grade_reviews.sql'])await db.exec(readFileSync(`supabase/migrations/${file}`,'utf8'));
},30000);
afterAll(async()=>{await db?.close();});
beforeEach(async()=>{await db.exec(`RESET ROLE;TRUNCATE cards CASCADE;TRUNCATE user_credits;INSERT INTO user_credits VALUES('${owner}',true,false,NULL);`);});
async function fixture(){const c=(await db.query<{id:string}>(`INSERT INTO cards(user_id,grade_status,conversational_grading,conversational_whole_grade,front_path,back_path,category,card_name) VALUES($1,'complete','{}',8,'f','b','sports','Test Card') RETURNING id`,[owner])).rows[0];const run=(await db.query<{id:string}>('SELECT id FROM card_grade_runs WHERE card_id=$1',[c.id])).rows[0];return{card:c.id,run:run.id};}
async function request(c:Awaited<ReturnType<typeof fixture>>,user=owner){return(await db.query<{id:string}>('SELECT request_card_grade_review($1,$2,$3,$4,$5) AS id',[c.card,user,c.run,[{category:'corners',side:'both'}],'Review corners'])).rows[0].id;}
async function complete(id:string,verdict='confirm',patch:unknown={},expected:unknown={}){return(await db.query<{result:{awaiting_owner?:boolean;stale?:boolean;already_recorded?:boolean}}>('SELECT complete_manual_grade_review($1,$2,$3,$4,$5,$6) AS result',[id,admin,verdict,'Confirmed visible wear on the back corners.',patch,expected])).rows[0].result;}
it('requires a purchase in the database and accepts active Card Lovers',async()=>{const c=await fixture();await db.exec(`UPDATE user_credits SET is_vip=false`);await expect(request(c)).rejects.toThrow('review_membership_required');await db.exec(`UPDATE user_credits SET is_card_lover=true,card_lover_current_period_end=now()-interval '1 day'`);await expect(request(c)).rejects.toThrow('review_membership_required');await db.exec(`UPDATE user_credits SET card_lover_current_period_end=now()+interval '1 day'`);expect(await request(c)).toBeTruthy();});
it('logs one request and one admin notification; old automatic workers cannot claim it',async()=>{const c=await fixture(),id=await request(c);expect(await request(c)).toBe(id);expect((await db.query('SELECT * FROM grade_review_notifications')).rows).toHaveLength(1);expect((await db.query<{job:unknown}>('SELECT claim_grade_review() AS job')).rows[0].job).toBeNull();expect((await db.query("SELECT * FROM card_grade_review_events WHERE event_type='requested'")).rows).toHaveLength(1);});
it('retains pending access after membership expiry and queues verdict mail exactly once',async()=>{const c=await fixture(),id=await request(c);await db.exec('UPDATE user_credits SET is_vip=false');expect(await request(c)).toBe(id);await complete(id);expect(await complete(id)).toMatchObject({already_recorded:true});expect((await db.query("SELECT * FROM grade_review_notifications WHERE kind='customer_reviewed'")).rows).toHaveLength(1);});
it('requires owner acceptance for both increases and decreases and preserves admin notes',async()=>{for(const grade of [9,7]){const c=await fixture(),id=await request(c);expect(await complete(id,'propose_change',{conversational_grading:'{"reviewed":true}',conversational_whole_grade:grade},{conversational_grading:'{}',conversational_whole_grade:8})).toMatchObject({awaiting_owner:true});expect((await db.query<{grade:string}>('SELECT conversational_whole_grade AS grade FROM cards WHERE id=$1',[c.card])).rows[0].grade).toBe('8');await db.query('SELECT decide_own_grade_review($1,$2,$3,$4)',[c.card,id,owner,'accept']);expect((await db.query<{grade:string}>('SELECT conversational_whole_grade AS grade FROM cards WHERE id=$1',[c.card])).rows[0].grade).toBe(String(grade));expect((await db.query<{customer_result:string}>('SELECT customer_result FROM card_grade_reviews WHERE id=$1',[id])).rows[0].customer_result).toContain('Confirmed visible wear');}});
it('rejects inactive admins and stale evidence without queuing completion email',async()=>{const c=await fixture(),id=await request(c);await expect(db.query('SELECT complete_manual_grade_review($1,$2,$3,$4,$5,$6)',[id,owner,'confirm','Sufficiently detailed notes.',{},{}])).rejects.toThrow('admin_required');await db.query("UPDATE cards SET conversational_grading='changed' WHERE id=$1",[c.card]);expect(await complete(id)).toMatchObject({stale:true});expect((await db.query("SELECT * FROM grade_review_notifications WHERE kind='customer_reviewed'")).rows).toHaveLength(0);});
it('prevents customer execution of admin completion and private queue reads',async()=>{await db.exec('SET ROLE authenticated');await expect(db.query('SELECT complete_manual_grade_review($1,$2,$3,$4,$5,$6)',[owner,admin,'confirm','Sufficiently detailed notes.',{},{}])).rejects.toThrow('permission denied');await expect(db.query('SELECT * FROM grade_review_notifications')).rejects.toThrow('permission denied');});
it('claims distinct notifications and quarantines retries before provider idempotency expires',async()=>{await request(await fixture());const first=(await db.query<{n:{id:string}}>('SELECT claim_grade_review_notification() AS n')).rows[0].n;expect(first.id).toBeTruthy();expect((await db.query<{n:unknown}>('SELECT claim_grade_review_notification() AS n')).rows[0].n).toBeNull();await db.exec("UPDATE grade_review_notifications SET first_attempt_at=now()-interval '24 hours',lease_expires_at=now()-interval '1 minute'");expect((await db.query<{n:unknown}>('SELECT claim_grade_review_notification() AS n')).rows[0].n).toBeNull();expect((await db.query<{last_error:string}>('SELECT last_error FROM grade_review_notifications')).rows[0].last_error).toBe('delivery_reconciliation_required');});
it('rolls back completion if its notification cannot be persisted',async()=>{const id=await request(await fixture());await db.exec(`CREATE FUNCTION fail_review_mail() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'test_outbox_failure'; END $$;CREATE TRIGGER fail_review_mail BEFORE INSERT ON grade_review_notifications FOR EACH ROW EXECUTE FUNCTION fail_review_mail();`);try{await expect(complete(id)).rejects.toThrow('test_outbox_failure');expect((await db.query<{status:string}>('SELECT status FROM card_grade_reviews WHERE id=$1',[id])).rows[0].status).toBe('queued');expect((await db.query("SELECT * FROM card_grade_review_events WHERE event_type='manual_review_completed'")).rows).toHaveLength(0);}finally{await db.exec('DROP TRIGGER fail_review_mail ON grade_review_notifications;DROP FUNCTION fail_review_mail();');}});
